### ISSUE TITLE
.png images

### ISSUE THREAD

**Issue by RebeccaWPerry** [jameskermode/aps-length#1]
Thanks for writing and sharing this package! It all worked once I switched my images from .png to .pdf to get ghostscript to stop complaining. If this is a problem for other people, it would be nice to say which image formats are supported or provide details on other workarounds. Thanks again... now to massively cut back my manuscript!!!

I added print statements at line 457:

```
        print bbox
        print type(bbox[3])
        print len(bbox[3])
```

and got the following output when the .png's were still being referenced: 

...
Abstract:      1163 chars (max 600)

Equations: [16]
['%%BoundingBox:', '2', '4', '230', '87']
<type 'str'>
3
Figure 1:       76 words (230x87 aspect 2.64, exptsystem.pdf)
['GPL', 'Ghostscript', '9.10:', 'Unrecoverable', 'error,', 'exit', 'code', '1']
<type 'str'>
13
Traceback (most recent call last):
  File "aps-length", line 569, in <module>
    process(tex_file, opts)
  File "aps-length", line 517, in process
    fig_words = count_figures_words(detex_lines, tex_lines, opts)
  File "aps-length", line 459, in count_figures_words
    width = float(bbox[3])
ValueError: could not convert string to float: Unrecoverable

**Comment by jameskermode** [comment]
Thanks for feedback. PNG images are supported by using the ImageMagick `identify' program to determine their aspect ratio rather than Ghostscript. You can do this with the --figs identify command line option. I added a sentence to the README and --help output to hopefully make this clearer.

**Comment by RebeccaWPerry** [comment]
Thanks. That makes sense now-- and is working with both a png figure version of my paper and a pdf figure version of my paper. One last thing that doesn't deserve an actual "issue"-- I found it useful to rename aps-length to be aps-length.py so that I can use autocompete when I type "python aps-<tab>" at a terminal. I made this change to my branch locally, but others might appreciate it as well.

**Comment by jameskermode** [comment]
Alternatively, you can install the script in your ~/bin directory (or somewhere else on your $PATH), and then you don't need to type "python", plus auto-complete should work.

**Comment by jameskermode** [comment]
Marking this issue as closed now

**Comment by RebeccaWPerry** [comment]
True, true, thanks! I hope many people find and use your very useful code!
