### ISSUE TITLE
Figure searching — Matching Names

### ISSUE THREAD

**Issue by arwinj** [jameskermode/aps-length#2]
Dear James,
Thank you for sharing this program.
I have included in my article figures with the following names : FIG1, FIG2, ..., FIG15 (using the comment \includegraphics{FIG1}). When launching the programe, in "count_figures_words", the line 417 search for the figure name in the article. As FIG1x start with the same characters than FIG1, the program quits with the following error :
`
file "./aps-length", line 421, in count_figures_words
    (inc_fig_line_no, inc_fig_line), = this_fig_lines
ValueError: too many values to unpack
`
as it has all figures staring with FIG1 in 'this_fig_lines'.

In this case, changing FIG1 to another name do the trick.
Best regards,

**Comment by jameskermode** [comment]
Thanks for this bug report. Should now be fixed - the code now looks for the first figure matching each name. This could potentially still cause problems if your figures are in a strange order, with e.g. FIG11 before FIG1 so let me know if you have any further problems and I'll figure out a more comprehensive solution.
