### ISSUE TITLE
Default to --figs identify?

### ISSUE THREAD

**Issue by DanHickstein** [jameskermode/aps-length#5]
Similar to Issue https://github.com/jameskermode/aps-length/issues/1, I was also confused when I initially tried to use aps-length to count my manuscript, which uses .png figures.

At the very least, it would be nice to have aps-length throw a more intelligible error than `ValueError: could not convert string to float: Unrecoverable`

Better yet, `identify` works for nearly any image format, including .pdf. So, why not default to `--figs identify`? Is the logic that most users already have ghostscript (is it installed with most tex distros?) and they would need to install ImageMagick? In that case, perhaps the best thing to do is to see if the user has `identify` available on the command line, and, if so, just use that?

**Comment by jameskermode** [comment]
Resolved by #6
